baseURL: "https://kerimdemirkaynak.github.io/"
title: Kerim Demirkaynak Blogu
copyright: "Â© [Kerim Demirkaynak](https://kerimdemirkaynak.github.io)"
pagination:
  pagerSize: 5
theme: [hugo-PaperMod]
defaultContentLanguage: "tr"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections:
  - "posts"
  - "papermod"

minify:
  disableXML: true

languages:
  tr:
    languageName: "TÃ¼rkÃ§e"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: ArÅŸiv
          url: archives
          weight: 5
        - name: Ara
          url: search/
          weight: 10
        - name: Etiketler
          url: tags/
          weight: 10
        - name: Ana Sayfa
          url: https://kerimdemirkaynak.github.io/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Kerim Demirkaynak Bloguâ€™nda teknoloji ve Ã§eviri dÃ¼nyasÄ±nÄ± keÅŸfedin"
  keywords: [Blog, YazÄ±lÄ±m, Anime, Manga, Fansub, AltyazÄ±, Yapay zeka, Teknoloji, Åablon tasarÄ±m, Anime Ã§eviri, Anime altyazÄ±, Anime haberleri]
  author: Kerim Demirkaynak
  defaultTheme: auto
  DateFormat: "2 January 2006"
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["https://kerimdemirkaynak.github.io/resimler/20241121_055155.jpg"]

  disqus:
    enable: true
    shortname: kerimdemirkaynak
    count: true

  params:
    title: Kerim'in Blogu
    comments: true

  assets:
    favicon: "https://kerimdemirkaynak.github.io/resimler/favicon.png"

  profileMode:
    enabled: false
    title: Kerim Demirkaynak
    imageUrl: "#"
    imageTitle: "Profil Resmi"
    buttons:
      - name: ArÅŸivler
        url: archives
      - name: Etiketler
        url: tags

  homeInfoParams:
    Title: "Kerim Demirkaynak"
    Content: "ğŸ‘‹ Bloguma hoÅŸ geldiniz! Anime, manga, fansub projeleri, yapay zeka ve tasarÄ±m Ã¼zerine iÃ§erikler paylaÅŸÄ±yorum. Teknolojiye ve Ã§eviri dÃ¼nyasÄ±na meraklÄ±ysan doÄŸru yerdesin! ğŸš€"

  socialIcons:
    - name: youtube
      title: "Profili YouTube'da GÃ¶rÃ¼ntÃ¼le"
      url: "https://youtube.com/@KerimDemirkaynak?sub_confirmation=1"
    - name: github
      title: "Profili GitHub'da GÃ¶rÃ¼ntÃ¼le"
      url: "https://github.com/KerimDemirkaynak"
    - name: X
      title: "Profili X'te GÃ¶rÃ¼ntÃ¼le"
      url: "http://x.com/KDxOFFICIAL"
    - name: instagram
      title: "Profili Instagram'da GÃ¶rÃ¼ntÃ¼le"
      url: "https://instagram.com/kerimdemirkaynak"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  x:
    disableInlineCSS: true
